In [293]:
import numpy as np
import pandas as pd
import statsmodels.formula.api as sm
import collections as cp
import random

In [294]:
dframe = pd.read_csv('Applestore.csv')

In [295]:
df = dframe.sample(100)

In [296]:
df = df.drop('size_bytes',axis = 1)

In [297]:
df = df.drop('user_rating',axis = 1)

In [298]:
df = df.drop('ver',axis = 1)

In [299]:
df = df.drop('currency', axis = 1)

In [300]:
df = df.drop('id', axis = 1)

In [301]:
df = df.drop('track_name', axis = 1)

In [302]:
df = df.drop('Unnamed: 0',axis=1)

In [303]:
df = df.drop('rating_count_tot',axis = 1)

In [304]:
df = df.drop('rating_count_ver',axis = 1)

In [305]:
df = df.drop('cont_rating',axis = 1)

In [306]:
df = df.drop('sup_devices.num',axis = 1)

In [307]:
df = df.drop('ipadSc_urls.num',axis = 1)

In [308]:
df = df.drop('lang.num',axis = 1)

In [309]:
df = df.drop('vpp_lic',axis = 1)

In [310]:
df = df.drop('prime_genre',axis = 1)

In [311]:
Full_data = df.copy()

In [286]:
Full_data

      price  user_rating_ver
206    0.99              3.5
549    0.00              0.0
2927   5.99              0.0
4709   0.00              0.0
2668   0.00              4.0
4760   0.00              3.0
1945   0.00              4.5
4324   2.99              3.5
3395   0.00              5.0
3351   0.00              4.5
6963   0.00              4.5
5525   0.00              3.5
6956   0.00              2.5
439    0.00              2.0
6129   0.00              4.5
145    0.99              4.5
2664   0.00              4.5
4947   0.00              0.0
3010   2.99              4.0
852    1.99              3.5
948    0.00              4.0
3390   0.99              4.0
5015   0.00              0.0
1974   6.99              4.5
1321   0.99              3.5
2149   0.00              5.0
5520   0.00              4.5
5901   0.00              2.5
4354   3.99              5.0
4438   0.00              4.5
...     ...              ...
1760   1.99              4.0
2163   0.00              4.5
3062   2.99              0.0
280    0.00              0.0
134    9.99              5.0
3587   0.00              3.0
6633   0.00              0.0
3080   3.99              4.5
3310   0.99              5.0
3742   1.99              4.0
4319   0.00              3.5
1208   0.00              2.5
3549   0.00              0.0
6071   0.00              0.0
1836   2.99              2.0
5378   0.00              3.5
5556   0.00              4.5
257    0.00              4.5
3108   0.00              4.5
2684   0.00              3.0
4155   0.00              0.0
6140   1.99              0.0
1985   0.00              4.0
4746   0.00              0.0
1035   0.00              5.0
844    2.99              0.0
5826   1.99              1.5
4101   0.99              5.0
3373   0.00              4.5
5077   2.99              0.0

[100 rows x 2 columns]

In [313]:
Full_data['user_rating_ver'].value_counts()

4.5    31
0.0    18
5.0    17
4.0    14
3.5     6
3.0     5
2.5     4
2.0     4
1.5     1
Name: user_rating_ver, dtype: int64

In [314]:
replaced = cp.defaultdict(set)
ix = [(row, col) for row in range(df.shape[0]) for col in range(df.shape[1]-1)]
random.shuffle(ix)
to_replace = int(round(.5*len(ix)))
for row, col in ix:
    if len(replaced[row]) < df.shape[1] - 1:
        df.iloc[row, col] = np.nan
        to_replace -= 1
        replaced[row].add(col)
        if to_replace == 0:
            break

In [315]:
df.isna().sum()

price              50
user_rating_ver     0
dtype: int64

In [316]:
##answer to 2a
df

      price  user_rating_ver
3044    NaN              0.0
4582    NaN              3.5
5704   0.00              0.0
691    0.00              5.0
6459    NaN              0.0
3738   0.00              3.5
6393    NaN              5.0
5896   0.00              5.0
73     0.00              4.5
7007    NaN              4.5
2054   0.00              4.5
3574    NaN              4.5
5535    NaN              4.5
4561   0.00              2.0
797     NaN              4.0
3630   3.99              4.0
6284   0.00              5.0
1335   0.00              5.0
3484    NaN              4.5
2287    NaN              4.5
6140    NaN              0.0
1458    NaN              4.5
1621   0.00              4.5
6278   0.00              0.0
2040   0.00              4.5
3456    NaN              4.5
2479   0.00              1.5
2030    NaN              4.0
6144   0.00              5.0
2575    NaN              4.5
...     ...              ...
1118   0.00              4.5
323    0.99              3.0
4530   0.00              0.0
6674    NaN              4.0
1874    NaN              4.5
4941   0.00              5.0
5107    NaN              4.5
3952    NaN              2.5
214     NaN              2.5
4696    NaN              4.0
1476   4.99              3.5
6173    NaN              4.0
1575   0.00              0.0
6584   0.00              2.0
6316    NaN              5.0
5299    NaN              4.0
1873    NaN              4.5
3784    NaN              5.0
4144   0.00              4.0
6500   4.99              5.0
4993   0.00              0.0
3978    NaN              3.0
4268    NaN              3.5
2601   2.99              5.0
2006   1.99              4.0
7067   0.00              3.0
1006    NaN              4.0
183     NaN              4.5
4244   0.00              4.5
223     NaN              4.5

[100 rows x 2 columns]

In [220]:
result2bdf = sm.ols(formula="price ~ user_rating_ver", data=df).fit()

In [317]:
result2bFull_data = sm.ols(formula="price ~ user_rating_ver", data=Full_data).fit()

In [320]:
##regression on larger set - 2b
print(result2bdf.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.060
Model:                            OLS   Adj. R-squared:                  0.040
Method:                 Least Squares   F-statistic:                     3.044
Date:                Tue, 20 Nov 2018   Prob (F-statistic):             0.0874
Time:                        11:54:55   Log-Likelihood:                -104.57
No. Observations:                  50   AIC:                             213.1
Df Residuals:                      48   BIC:                             217.0
Df Model:                           1
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           0.8395      0.556      1.510      0.138      -0.279       1.957
user_rating_ver     0.2627      0.151      1.745      0.087      -0.040       0.565
==============================================================================
Omnibus:                        6.120   Durbin-Watson:                   2.344
Prob(Omnibus):                  0.047   Jarque-Bera (JB):                5.899
Skew:                           0.840   Prob(JB):                       0.0524
Kurtosis:                       2.920   Cond. No.                         7.66
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [322]:
##regression on smaller set with missing values - 2b
##looking at these two datasets shows that most of the variables are different by a factor of 2. This is appropriate because there's half as many data points in the one with missing data. 

print(result2bFull_data.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     3.130
Date:                Tue, 20 Nov 2018   Prob (F-statistic):             0.0800
Time:                        11:56:07   Log-Likelihood:                -176.13
No. Observations:                 100   AIC:                             356.3
Df Residuals:                      98   BIC:                             361.5
Df Model:                           1
Covariance Type:            nonrobust
===================================================================================
                      coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
Intercept           0.4056      0.307      1.323      0.189      -0.203       1.014
user_rating_ver     0.1431      0.081      1.769      0.080      -0.017       0.304
==============================================================================
Omnibus:                       39.333   Durbin-Watson:                   2.203
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               72.203
Skew:                           1.677   Prob(JB):                     2.10e-16
Kurtosis:                       5.466   Cond. No.                         8.63
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [323]:
result2cFull_data = sm.ols(formula="user_rating_ver ~ price", data=Full_data).fit()

In [324]:
result2cdf = sm.ols(formula="user_rating_ver ~ price", data=df).fit()

In [326]:
##2c
print(result2cFull_data.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        user_rating_ver   R-squared:                       0.031
Model:                            OLS   Adj. R-squared:                  0.021
Method:                 Least Squares   F-statistic:                     3.130
Date:                Tue, 20 Nov 2018   Prob (F-statistic):             0.0800
Time:                        11:57:58   Log-Likelihood:                -196.82
No. Observations:                 100   AIC:                             397.6
Df Residuals:                      98   BIC:                             402.8
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      3.1682      0.206     15.394      0.000       2.760       3.577
price          0.2164      0.122      1.769      0.080      -0.026       0.459
==============================================================================
Omnibus:                       14.689   Durbin-Watson:                   1.926
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               17.693
Skew:                          -1.020   Prob(JB):                     0.000144
Kurtosis:                       2.705   Cond. No.                         2.23
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [328]:
##2c By switching the dependent and independent variables, it is worth noting that the relationship based on the factor of 2 does not hold fast. 
print(result2cdf.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:        user_rating_ver   R-squared:                       0.082
Model:                            OLS   Adj. R-squared:                  0.063
Method:                 Least Squares   F-statistic:                     4.279
Date:                Tue, 20 Nov 2018   Prob (F-statistic):             0.0440
Time:                        11:59:14   Log-Likelihood:                -101.86
No. Observations:                  50   AIC:                             207.7
Df Residuals:                      48   BIC:                             211.5
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      2.8440      0.304      9.366      0.000       2.233       3.455
price          0.4017      0.194      2.068      0.044       0.011       0.792
==============================================================================
Omnibus:                       14.317   Durbin-Watson:                   2.173
Prob(Omnibus):                  0.001   Jarque-Bera (JB):                5.374
Skew:                          -0.536   Prob(JB):                       0.0681
Kurtosis:                       1.804   Cond. No.                         2.00
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [332]:
export_csv = df.to_csv (r'C:\Users\marka\Desktop\GitHub\MEM_FDS_Fall18_Lab_Tutorials\export_dataframe.csv', index = None, header=True)

',price,user_rating_ver\n3044,0.0,0.0\n4582,0.0,3.5\n5704,0.0,0.0\n691,0.0,5.0\n6459,0.0,0.0\n3738,0.0,3.5\n6393,2.99,5.0\n5896,0.0,5.0\n73,0.0,4.5\n7007,2.99,4.5\n2054,0.0,4.5\n3574,0.0,4.5\n5535,0.0,4.5\n4561,0.0,2.0\n797,2.99,4.0\n3630,3.99,4.0\n6284,0.0,5.0\n1335,0.0,5.0\n3484,0.0,4.5\n2287,0.99,4.5\n6140,1.99,0.0\n1458,0.0,4.5\n1621,0.0,4.5\n6278,0.0,0.0\n2040,0.0,4.5\n3456,0.0,4.5\n2479,0.0,1.5\n2030,1.99,4.0\n6144,0.0,5.0\n2575,0.0,4.5\n6844,0.0,4.5\n367,3.99,5.0\n4028,0.0,0.0\n2714,0.0,4.5\n5314,0.0,4.5\n5060,0.99,3.0\n4327,0.0,4.0\n2171,2.99,4.0\n6762,0.99,3.5\n1680,0.0,5.0\n4955,3.99,4.5\n92,0.0,4.0\n2164,0.0,0.0\n2045,1.99,4.5\n3162,0.99,5.0\n6302,0.0,0.0\n5437,0.0,0.0\n3748,0.0,2.0\n2403,0.0,5.0\n1077,2.99,4.0\n2892,0.0,2.5\n1239,0.99,4.5\n4369,0.0,2.5\n5632,0.0,0.0\n4398,1.99,4.5\n896,0.0,0.0\n5937,0.0,5.0\n1376,0.99,4.5\n4279,0.99,3.5\n5332,0.0,0.0\n796,0.0,0.0\n6610,0.99,0.0\n4641,1.99,4.5\n3113,0.99,4.5\n6594,5.99,0.0\n6418,0.99,3.0\n4627,0.99,2.0\n98,2.99,4.5\n7011,0.0,4.5\n3291,2.99,5.0\n1118,0.0,4.5\n323,0.99,3.0\n4530,0.0,0.0\n6674,0.0,4.0\n1874,0.0,4.5\n4941,0.0,5.0\n5107,0.99,4.5\n3952,0.0,2.5\n214,0.0,2.5\n4696,0.0,4.0\n1476,4.99,3.5\n6173,0.0,4.0\n1575,0.0,0.0\n6584,0.0,2.0\n6316,0.0,5.0\n5299,1.99,4.0\n1873,2.99,4.5\n3784,0.0,5.0\n4144,0.0,4.0\n6500,4.99,5.0\n4993,0.0,0.0\n3978,0.0,3.0\n4268,0.0,3.5\n2601,2.99,5.0\n2006,1.99,4.0\n7067,0.0,3.0\n1006,4.99,4.0\n183,1.99,4.5\n4244,0.0,4.5\n223,0.0,4.5\n'